name: Neural Network Workflow

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/Checkout@v4

    - name: Set up Python
      uses: actions/setup-Python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true

    - name: Cache poetry dependencies
      uses: actions/Cache@v4
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install project dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry run make install