name: Neural Network Workflow

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/Checkout@v4

    - name: Set up Python
      uses: actions/setup-Python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      uses: snok/install-poetry@v2

    - name: Install project dependencies
      run: poetry run make install